create sequence plan_data_seq;
CREATE TABLE public.plan_data (
                                  plan_id integer DEFAULT nextval(('plan_data_seq'::text)::regclass) NOT NULL,
                                  client_id integer NOT NULL,
                                  plan_name character varying(100),
                                  plan_date date DEFAULT to_date(textcat((date_part('year'::text, now()))::text, '-01-01'::text), 'YYYY-MM-DD'::text) NOT NULL,
                                  preparer_name character varying(50),
                                  preparer_address character varying(255),
                                  preparer_phone character varying(30),
                                  contract_date date,
                                  notes text,
                                  acc_method smallint DEFAULT 0 NOT NULL,
                                  di_rate double precision DEFAULT 7 NOT NULL,
                                  amort smallint DEFAULT 15 NOT NULL,
                                  sec_415_limit double precision DEFAULT 140000 NOT NULL,
                                  sec_415_inflation double precision DEFAULT 4 NOT NULL,
                                  ss_inflation double precision DEFAULT 4 NOT NULL,
                                  fica_interest double precision DEFAULT 6.1 NOT NULL,
                                  plan_period smallint DEFAULT 0 NOT NULL,
                                  av_date date,
                                  period_start date DEFAULT to_date(textcat((date_part('year'::text, now()))::text, '-01-01'::text), 'YYYY-MM-DD'::text) NOT NULL,
                                  period_end date DEFAULT to_date(textcat((date_part('year'::text, now()))::text, '-12-31'::text), 'YYYY-MM-DD'::text) NOT NULL,
                                  credit_method smallint DEFAULT 0 NOT NULL,
                                  credit_day smallint DEFAULT 1 NOT NULL,
                                  vesting_code smallint DEFAULT 0 NOT NULL,
                                  accounting_history_start date,
                                  accounting_history_end date,
                                  accounting_current_start date,
                                  accounting_current_end date,
                                  matching_code character varying(20),
                                  web_access_code smallint DEFAULT 0 NOT NULL,
                                  description character varying(50),
                                  web_trans_lock_code smallint DEFAULT 0 NOT NULL,
                                  web_trans_lock_date date DEFAULT to_date(textcat((date_part('year'::text, now()))::text, '-01-01'::text), 'YYYY-MM-DD'::text) NOT NULL,
                                  ignore_div_and_cg_code smallint DEFAULT 0 NOT NULL,
                                  reallocation_code smallint DEFAULT 1 NOT NULL,
                                  fork_accounts_code smallint DEFAULT 1 NOT NULL,
                                  fork_old_new_code smallint DEFAULT 1 NOT NULL,
                                  transfer_code smallint DEFAULT 1 NOT NULL,
                                  transfer_type_code smallint DEFAULT 0 NOT NULL,
                                  frequency_code smallint DEFAULT 0 NOT NULL,
                                  frequency_amount smallint DEFAULT 0 NOT NULL,
                                  normal_pricing_code smallint DEFAULT 0 NOT NULL,
                                  normal_pricing_date date DEFAULT to_date(textcat((date_part('year'::text, now()))::text, '-01-01'::text), 'YYYY-MM-DD'::text) NOT NULL,
                                  basic_rate_code smallint DEFAULT 0 NOT NULL,
                                  projection_code smallint DEFAULT 0 NOT NULL,
                                  plan_admin_id integer,
                                  reallocation_effective_code smallint DEFAULT 0 NOT NULL,
                                  dist_effective_code smallint DEFAULT 0 NOT NULL,
                                  ignore_div_and_cg_date date,
                                  reallocation_timing_code smallint DEFAULT 0 NOT NULL,
                                  reallocation_timing_day smallint DEFAULT 1 NOT NULL,
                                  percent_increment smallint DEFAULT 0 NOT NULL,
                                  hide_vesting_code smallint DEFAULT 0 NOT NULL,
                                  prdb_display_code smallint DEFAULT 0 NOT NULL,
                                  status_code smallint DEFAULT 0 NOT NULL,
                                  tpc_document_code smallint DEFAULT 0 NOT NULL,
                                  est_fees smallint DEFAULT 0 NOT NULL,
                                  admin_id integer,
                                  benefit_type_code smallint DEFAULT 0 NOT NULL,
                                  funding_type_code smallint DEFAULT 0 NOT NULL,
                                  rabbi_trust_code smallint DEFAULT 0 NOT NULL,
                                  trustee character varying(100),
                                  carrier_id integer,
                                  reviewed_409a smallint,
                                  conclusion_409a smallint,
                                  notes_409a text,
                                  webaccess_generic_link_text character varying(100),
                                  webaccess_generic_link_url character varying(255),
                                  webaccess_generic_contact_text character varying(100),
                                  webaccess_generic_contact_email character varying(100),
                                  projection_years smallint DEFAULT 25 NOT NULL,
                                  frequency_insurance_accounting integer,
                                  frequency_benefit_accounting integer,
                                  frequency_benefit_statements integer,
                                  dol_letter_filed smallint DEFAULT 0 NOT NULL,
                                  dol_letter_date date,
                                  benefit_statement character varying(150),
                                  include_proj_dist_code smallint DEFAULT 0 NOT NULL,
                                  distribution_wait_time smallint,
                                  contribution_stop_time smallint,
                                  contingent_dist_same_code smallint,
                                  limit_inservice_accounts smallint,
                                  num_inservice_accounts smallint,
                                  when_create_new_account smallint,
                                  all_sos_options_same smallint DEFAULT 0,
                                  transition_fasb158_date date DEFAULT '2006-12-15'::date,
                                  send_409a_letter smallint,
                                  benefit_subtype_code smallint DEFAULT 0 NOT NULL,
                                  display_trueup_report smallint,
                                  web_mirror_dist_option_code smallint DEFAULT 0 NOT NULL,
                                  db_accounting_type smallint DEFAULT 0 NOT NULL,
                                  min_account_allocation_percent smallint DEFAULT 0 NOT NULL,
                                  asset_reallocation_threshold double precision,
                                  immediate_recognition_code smallint DEFAULT 0 NOT NULL,
                                  immediate_recognition_date date,
                                  display_individual_trueups_code smallint DEFAULT 0,
                                  check_asset_liability_code smallint DEFAULT 0,
                                  mf_accounting_method smallint DEFAULT 0 NOT NULL,
                                  mf_inventory_costing_mthd_def smallint DEFAULT 0 NOT NULL,
                                  mf_reinvest_dividends_def smallint DEFAULT 0 NOT NULL,
                                  mf_reinvest_capital_gains_def smallint DEFAULT 0 NOT NULL,
                                  mf_div_apply_70pc_tax_exclusion_def smallint DEFAULT 0 NOT NULL,
                                  mf_capital_gain_tax_rate_def double precision DEFAULT 15.00,
                                  db_basis_avg_working_life integer DEFAULT 1 NOT NULL,
                                  db_vesting_equals_al smallint DEFAULT 0,
                                  display_manual_enrollments_code smallint DEFAULT 0 NOT NULL,
                                  proj_dist_start date,
                                  proj_dist_end date,
                                  cash_value_report_code smallint DEFAULT 0 NOT NULL,
                                  display_irr_code smallint DEFAULT 1 NOT NULL,
                                  distribution_max_wait_time_code smallint DEFAULT 0 NOT NULL,
                                  distribution_max_wait_time_age smallint DEFAULT 65 NOT NULL,
                                  distribution_max_wait_time_months smallint DEFAULT 0 NOT NULL,
                                  db_display_age_code smallint DEFAULT 0 NOT NULL,
                                  web_mirror_bene_change_code smallint DEFAULT 1 NOT NULL,
                                  compliance_plan_code smallint DEFAULT 0,
                                  ignore_for_compliance_code smallint DEFAULT 0 NOT NULL,
                                  net_csv_accounting_code smallint DEFAULT 0 NOT NULL,
                                  web_enable_policy_code smallint DEFAULT 0 NOT NULL,
                                  reallocation_custom_notes text,
                                  db_life_expectancy_at_code smallint DEFAULT 0 NOT NULL,
                                  db_post_ret_sd_acct_start_date date,
                                  db_pre_ret_decrement_code smallint DEFAULT 0 NOT NULL,
                                  db_post_ret_decrement_code smallint DEFAULT 0 NOT NULL,
                                  scheduled_dist_elections_same_code smallint DEFAULT 0 NOT NULL,
                                  db_post_ret_decrement_start_date date,
                                  eitf_accounting_method_code smallint,
                                  eitf_method_code smallint,
                                  product_fund_id integer,
                                  dist_proj_report_with_full_vest_code integer DEFAULT 0 NOT NULL,
                                  db_avg_life_active_parts_only_code smallint DEFAULT 1 NOT NULL,
                                  al_monitoring_freq_code smallint DEFAULT 2,
                                  al_days_to_fallback smallint DEFAULT 5,
                                  proj_cont_for_fica_code smallint DEFAULT 0 NOT NULL,
                                  al_auto_rebalance_code smallint DEFAULT 0 NOT NULL,
                                  al_reallocation_type_code smallint DEFAULT 2 NOT NULL,
                                  al_breakdown_fund_of_funds_code smallint DEFAULT 0 NOT NULL,
                                  display_dist_info_code smallint DEFAULT 1 NOT NULL,
                                  batch_process_eeri_code smallint DEFAULT 0,
                                  db_display_fica_vested_percent_code smallint DEFAULT 1 NOT NULL,
                                  allow_redeferrals smallint DEFAULT 0,
                                  is_evergreen smallint DEFAULT 0,
                                  web_enable_db_code smallint DEFAULT 0 NOT NULL,
                                  enrollment_send_begins_soon_code smallint DEFAULT 0 NOT NULL,
                                  enrollment_send_open_code smallint DEFAULT 0 NOT NULL,
                                  enrollment_send_reminder_code smallint DEFAULT 0 NOT NULL,
                                  enrollment_send_ended_code smallint DEFAULT 0 NOT NULL,
                                  custom_admin_link_text character varying(100),
                                  custom_admin_link_url character varying(255),
                                  mirror_reporting_automation_code smallint DEFAULT 0,
                                  creation_timestamp timestamp without time zone DEFAULT now(),
                                  db_fica_method_code smallint DEFAULT 1 NOT NULL,
                                  db_fica_method_transition_date date,
                                  service_termination_reason_code smallint,
                                  service_termination_date date,
                                  memo_processing_automation_code smallint DEFAULT 0 NOT NULL,
                                  memo_accnt_balance_based_on_code smallint,
                                  memo_transaction_type_code smallint,
                                  memo_transfers_fund_list_id integer,
                                  memo_use_value_as_of_code smallint,
                                  memo_treatment_of_loans_code smallint,
                                  db_reporting_automation_code smallint DEFAULT 0,
                                  enforce_frequent_trading_policy_code smallint DEFAULT 0,
                                  display_redeferral_online_code smallint DEFAULT 0,
                                  redeferral_payment_type_code smallint DEFAULT 0,
                                  limit_redeferral_period_code smallint DEFAULT 0,
                                  redeferral_period_maximum_age_years smallint,
                                  redeferral_period_maximum_age_months smallint,
                                  redeferral_maximum_period_in_months smallint,
                                  service_constraint_code smallint DEFAULT 0,
                                  service_constraint_age_years smallint,
                                  service_constraint_age_months smallint,
                                  redeferral_limit_code smallint DEFAULT 0,
                                  number_of_redeferrals_allowed smallint,
                                  send_redeferral_reminder_email smallint DEFAULT 0,
                                  db_fica_projection_code integer DEFAULT 0,
                                  db_fica_years_to_project integer DEFAULT 0,
                                  policy_plan_id integer,
                                  mirror_send_fund_change_emails_to_participants_code smallint DEFAULT 0,
                                  mortality_table_id integer,
                                  CONSTRAINT "$1" CHECK ((period_start > '1899-12-31'::date)),
                                  CONSTRAINT "$2" CHECK ((period_end > '1899-12-31'::date)),
                                  CONSTRAINT "$3" CHECK ((credit_day > 0)),
                                  CONSTRAINT "$4" CHECK ((web_trans_lock_date > '1899-12-31'::date)),
                                  CONSTRAINT "$5" CHECK ((normal_pricing_date > '1899-12-31'::date)),
                                  CONSTRAINT plan_data_amort CHECK ((amort >= 0)),
                                  CONSTRAINT plan_data_mf_accounting_method_check CHECK (((mf_accounting_method >= 0) AND (mf_accounting_method <= 2))),
                                  CONSTRAINT plan_data_mf_capital_gain_tax_rate_def_check CHECK ((mf_capital_gain_tax_rate_def > (0.00)::double precision)),
                                  CONSTRAINT plan_data_mf_div_apply_70pc_tax_exclusion_def_check CHECK (((mf_div_apply_70pc_tax_exclusion_def >= 0) AND (mf_div_apply_70pc_tax_exclusion_def <= 2))),
                                  CONSTRAINT plan_data_mf_inventory_costing_mthd_def_check CHECK (((mf_inventory_costing_mthd_def >= 0) AND (mf_inventory_costing_mthd_def <= 2))),
                                  CONSTRAINT plan_data_mf_reinvest_capital_gains_def_check CHECK (((mf_reinvest_capital_gains_def >= 0) AND (mf_reinvest_capital_gains_def <= 2))),
                                  CONSTRAINT plan_data_mf_reinvest_dividends_def_check CHECK (((mf_reinvest_dividends_def >= 0) AND (mf_reinvest_dividends_def <= 2))),
                                  CONSTRAINT plan_data_plan_date CHECK ((plan_date > '1899-12-31'::date)),
                                  CONSTRAINT plan_data_sec_415_limit CHECK ((sec_415_limit >= (0)::double precision))
);


ALTER TABLE public.plan_data OWNER TO postgres;

--
-- Name: plan_data plan_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_data
    ADD CONSTRAINT plan_data_pkey PRIMARY KEY (plan_id);


--
-- Name: plan_data plan_unique_matching_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_data
    ADD CONSTRAINT plan_unique_matching_code UNIQUE (matching_code);


--
-- Name: plan_data_client_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX plan_data_client_id_idx ON public.plan_data USING btree (client_id);


--
-- Name: plan_data_plan_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX plan_data_plan_name_idx ON public.plan_data USING btree (plan_name);


--
-- Name: plan_data $6; Type: FK CONSTRAINT; Schema: public; Owner: postgres